### ISSUE TITLE
Decide what C++ Standard should be used

### ISSUE THREAD

**Issue by offa** [offa/danek#2]
Decide what C++ Standard should be used – **_C++11_** or **_C++14_**?

**Comment by tarTG** [comment]
I would suggest C++14. 
With this fork, you want to modernize the library, why then stuck back to C++11?
Most Compiler do support C++14 (even MSVC in most parts since 1015).
And you can do some stuff much more elegant, like C++11 has only single statement `constexpr `functions.

**Comment by offa** [comment]
I've considert C++11 only, as not all projects have upgrade to 14 yet. But yes, you are right, C++14 is now available for years, why stuck to C++11?

Finally, it'll be C++14.
